// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as config$0 from "../config/models.js";

/**
 * DatabaseConnection 与 config 包中的结构保持一致
 */
export const DatabaseConnection = config$0.DatabaseConnection;

/**
 * DatabaseConnection 与 config 包中的结构保持一致
 * @typedef {config$0.DatabaseConnection} DatabaseConnection
 */

/**
 * ExportSettings 导出设置结构，与 config 包中的结构保持一致
 */
export const ExportSettings = config$0.ExportSettings;

/**
 * ExportSettings 导出设置结构，与 config 包中的结构保持一致
 * @typedef {config$0.ExportSettings} ExportSettings
 */

export class ImportConflict {
    /**
     * Creates a new ImportConflict instance.
     * @param {Partial<ImportConflict>} [$$source = {}] - The source object to create the ImportConflict.
     */
    constructor($$source = {}) {
        if (!("schema" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["schema"] = "";
        }
        if (!("tables" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["tables"] = [];
        }
        if (!("views" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["views"] = [];
        }
        if (!("events" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["events"] = [];
        }
        if (!("functions" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["functions"] = [];
        }
        if (!("procedures" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["procedures"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ImportConflict instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ImportConflict}
     */
    static createFrom($$source = {}) {
        const $$createField1_0 = $$createType0;
        const $$createField2_0 = $$createType0;
        const $$createField3_0 = $$createType0;
        const $$createField4_0 = $$createType0;
        const $$createField5_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("tables" in $$parsedSource) {
            $$parsedSource["tables"] = $$createField1_0($$parsedSource["tables"]);
        }
        if ("views" in $$parsedSource) {
            $$parsedSource["views"] = $$createField2_0($$parsedSource["views"]);
        }
        if ("events" in $$parsedSource) {
            $$parsedSource["events"] = $$createField3_0($$parsedSource["events"]);
        }
        if ("functions" in $$parsedSource) {
            $$parsedSource["functions"] = $$createField4_0($$parsedSource["functions"]);
        }
        if ("procedures" in $$parsedSource) {
            $$parsedSource["procedures"] = $$createField5_0($$parsedSource["procedures"]);
        }
        return new ImportConflict(/** @type {Partial<ImportConflict>} */($$parsedSource));
    }
}

export class ImportConflictCheckResult {
    /**
     * Creates a new ImportConflictCheckResult instance.
     * @param {Partial<ImportConflictCheckResult>} [$$source = {}] - The source object to create the ImportConflictCheckResult.
     */
    constructor($$source = {}) {
        if (!("has_conflicts" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["has_conflicts"] = false;
        }
        if (!("conflicts" in $$source)) {
            /**
             * @member
             * @type {ImportConflict[]}
             */
            this["conflicts"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ImportConflictCheckResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ImportConflictCheckResult}
     */
    static createFrom($$source = {}) {
        const $$createField1_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("conflicts" in $$parsedSource) {
            $$parsedSource["conflicts"] = $$createField1_0($$parsedSource["conflicts"]);
        }
        return new ImportConflictCheckResult(/** @type {Partial<ImportConflictCheckResult>} */($$parsedSource));
    }
}

/**
 * ProcessInfo 进程信息结构体
 */
export class ProcessInfo {
    /**
     * Creates a new ProcessInfo instance.
     * @param {Partial<ProcessInfo>} [$$source = {}] - The source object to create the ProcessInfo.
     */
    constructor($$source = {}) {
        if (!("PID" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["PID"] = 0;
        }
        if (!("Name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["Name"] = "";
        }
        if (!("Cmdline" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["Cmdline"] = "";
        }
        if (!("CPUPercent" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["CPUPercent"] = 0;
        }
        if (!("MemoryMB" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["MemoryMB"] = 0;
        }
        if (!("ListenAddr" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["ListenAddr"] = "";
        }
        if (!("ListenPort" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["ListenPort"] = 0;
        }
        if (!("Status" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["Status"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ProcessInfo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ProcessInfo}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ProcessInfo(/** @type {Partial<ProcessInfo>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = ImportConflict.createFrom;
const $$createType2 = $Create.Array($$createType1);
