// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * DatabaseService 数据库操作 Wails 服务
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as config$0 from "./internal/config/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as tools$0 from "./internal/tools/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * AddDatabaseConnection 添加数据库连接信息
 * @param {tools$0.DatabaseConnection} conn
 * @returns {$CancellablePromise<void>}
 */
export function AddDatabaseConnection(conn) {
    return $Call.ByID(681567886, conn);
}

/**
 * CheckImportConflicts 检查导入冲突
 * @param {$models.CheckImportConflictsRequest} req
 * @returns {$CancellablePromise<tools$0.ImportConflictCheckResult>}
 */
export function CheckImportConflicts(req) {
    return $Call.ByID(4279217216, req).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * ConnectDatabase 使用 mysqlshell 连接数据库
 * @param {tools$0.DatabaseConnection} conn
 * @returns {$CancellablePromise<void>}
 */
export function ConnectDatabase(conn) {
    return $Call.ByID(1718593575, conn);
}

/**
 * DeleteDatabaseConnection 删除数据库连接信息
 * @param {string} id
 * @returns {$CancellablePromise<void>}
 */
export function DeleteDatabaseConnection(id) {
    return $Call.ByID(2869744862, id);
}

/**
 * DropConflictingTables 删除冲突表
 * @param {$models.DropConflictingTablesRequest} req
 * @returns {$CancellablePromise<void>}
 */
export function DropConflictingTables(req) {
    return $Call.ByID(3584965684, req);
}

/**
 * ExportDatabases 导出数据库（使用MySQL Shell）
 * @param {$models.ExportRequest} req
 * @returns {$CancellablePromise<$models.ExportResponse>}
 */
export function ExportDatabases(req) {
    return $Call.ByID(966440068, req).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * ExportDatabasesMySQLDump 使用 mysqldump 导出多个数据库
 * @param {$models.MySQLDumpExportRequest} req
 * @returns {$CancellablePromise<$models.ExportResponse>}
 */
export function ExportDatabasesMySQLDump(req) {
    return $Call.ByID(602480072, req).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * ExportTables 导出表（使用MySQL Shell）
 * @param {$models.ExportRequest} req
 * @returns {$CancellablePromise<$models.ExportResponse>}
 */
export function ExportTables(req) {
    return $Call.ByID(2303386255, req).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * ExportTablesMySQLDump 使用 mysqldump 导出指定表
 * @param {$models.MySQLDumpExportRequest} req
 * @returns {$CancellablePromise<$models.ExportResponse>}
 */
export function ExportTablesMySQLDump(req) {
    return $Call.ByID(1690723905, req).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * GetDatabaseConnection 根据 ID 获取数据库连接信息
 * @param {string} id
 * @returns {$CancellablePromise<tools$0.DatabaseConnection>}
 */
export function GetDatabaseConnection(id) {
    return $Call.ByID(1078606881, id).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * GetDatabaseConnections 获取所有数据库连接信息
 * @returns {$CancellablePromise<tools$0.DatabaseConnection[]>}
 */
export function GetDatabaseConnections() {
    return $Call.ByID(2262627606).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * GetExportSettings 获取导出设置
 * @returns {$CancellablePromise<tools$0.ExportSettings>}
 */
export function GetExportSettings() {
    return $Call.ByID(3481110387).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType4($result);
    }));
}

/**
 * ImportDatabases 导入数据库（使用MySQL Shell）
 * @param {$models.ImportRequest} req
 * @returns {$CancellablePromise<$models.ImportResponse>}
 */
export function ImportDatabases(req) {
    return $Call.ByID(2660187637, req).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType5($result);
    }));
}

/**
 * ImportDumpMySQLDump 使用 mysql 导入 SQL 文件
 * @param {$models.MySQLDumpImportRequest} req
 * @returns {$CancellablePromise<$models.ImportResponse>}
 */
export function ImportDumpMySQLDump(req) {
    return $Call.ByID(1867858613, req).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType5($result);
    }));
}

/**
 * ImportTables 导入表（使用MySQL Shell）
 * @param {$models.ImportRequest} req
 * @returns {$CancellablePromise<$models.ImportResponse>}
 */
export function ImportTables(req) {
    return $Call.ByID(2081685104, req).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType5($result);
    }));
}

/**
 * ListDatabases 查询数据库列表
 * @param {tools$0.DatabaseConnection} conn
 * @returns {$CancellablePromise<string[]>}
 */
export function ListDatabases(conn) {
    return $Call.ByID(4087710774, conn).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType6($result);
    }));
}

/**
 * ListDatabasesMySQLDump 使用 mysqldump 工具查询数据库列表
 * @param {tools$0.DatabaseConnection} conn
 * @returns {$CancellablePromise<string[]>}
 */
export function ListDatabasesMySQLDump(conn) {
    return $Call.ByID(2544675730, conn).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType6($result);
    }));
}

/**
 * ListTables 查询指定数据库下的表列表
 * @param {tools$0.DatabaseConnection} conn
 * @returns {$CancellablePromise<string[]>}
 */
export function ListTables(conn) {
    return $Call.ByID(4175186377, conn).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType6($result);
    }));
}

/**
 * ListTablesMySQLDump 使用 mysqldump 工具查询表列表
 * @param {tools$0.DatabaseConnection} conn
 * @returns {$CancellablePromise<string[]>}
 */
export function ListTablesMySQLDump(conn) {
    return $Call.ByID(416770547, conn).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType6($result);
    }));
}

/**
 * SaveExportSettings 保存导出设置
 * @param {tools$0.ExportSettings} settings
 * @returns {$CancellablePromise<void>}
 */
export function SaveExportSettings(settings) {
    return $Call.ByID(1926450538, settings);
}

/**
 * Startup 应用启动时由 Wails 调用
 * @returns {$CancellablePromise<void>}
 */
export function Startup() {
    return $Call.ByID(2917451893);
}

/**
 * UpdateDatabaseConnection 更新数据库连接信息
 * @param {tools$0.DatabaseConnection} conn
 * @returns {$CancellablePromise<void>}
 */
export function UpdateDatabaseConnection(conn) {
    return $Call.ByID(2112912848, conn);
}

// Private type creation functions
const $$createType0 = tools$0.ImportConflictCheckResult.createFrom;
const $$createType1 = $models.ExportResponse.createFrom;
const $$createType2 = config$0.DatabaseConnection.createFrom;
const $$createType3 = $Create.Array($$createType2);
const $$createType4 = config$0.ExportSettings.createFrom;
const $$createType5 = $models.ImportResponse.createFrom;
const $$createType6 = $Create.Array($Create.Any);
