// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * DialogService 对话框 Wails 服务
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

/**
 * SelectFile 打开系统文件选择对话框
 * @returns {$CancellablePromise<string>}
 */
export function SelectFile() {
    return $Call.ByID(1516739515);
}

/**
 * SelectFolder 打开系统文件夹选择对话框
 * @returns {$CancellablePromise<string>}
 */
export function SelectFolder() {
    return $Call.ByID(4284558709);
}

/**
 * SelectSaveFile 打开系统保存文件对话框
 * @param {string} defaultName
 * @returns {$CancellablePromise<string>}
 */
export function SelectSaveFile(defaultName) {
    return $Call.ByID(4085310198, defaultName);
}

/**
 * Startup 应用启动时由 Wails 调用
 * @returns {$CancellablePromise<void>}
 */
export function Startup() {
    return $Call.ByID(2397186394);
}
