// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as tools$0 from "./internal/tools/models.js";

/**
 * CheckImportConflictsRequest 检查导入冲突请求结构
 */
export class CheckImportConflictsRequest {
    /**
     * Creates a new CheckImportConflictsRequest instance.
     * @param {Partial<CheckImportConflictsRequest>} [$$source = {}] - The source object to create the CheckImportConflictsRequest.
     */
    constructor($$source = {}) {
        if (!("connection_id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["connection_id"] = "";
        }
        if (!("input_dir" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["input_dir"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CheckImportConflictsRequest instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {CheckImportConflictsRequest}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new CheckImportConflictsRequest(/** @type {Partial<CheckImportConflictsRequest>} */($$parsedSource));
    }
}

/**
 * DropConflictingTablesRequest 删除冲突表请求结构
 */
export class DropConflictingTablesRequest {
    /**
     * Creates a new DropConflictingTablesRequest instance.
     * @param {Partial<DropConflictingTablesRequest>} [$$source = {}] - The source object to create the DropConflictingTablesRequest.
     */
    constructor($$source = {}) {
        if (!("connection_id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["connection_id"] = "";
        }
        if (!("conflicts" in $$source)) {
            /**
             * @member
             * @type {tools$0.ImportConflict[]}
             */
            this["conflicts"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DropConflictingTablesRequest instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {DropConflictingTablesRequest}
     */
    static createFrom($$source = {}) {
        const $$createField1_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("conflicts" in $$parsedSource) {
            $$parsedSource["conflicts"] = $$createField1_0($$parsedSource["conflicts"]);
        }
        return new DropConflictingTablesRequest(/** @type {Partial<DropConflictingTablesRequest>} */($$parsedSource));
    }
}

/**
 * ExportRequest 导出请求结构
 */
export class ExportRequest {
    /**
     * Creates a new ExportRequest instance.
     * @param {Partial<ExportRequest>} [$$source = {}] - The source object to create the ExportRequest.
     */
    constructor($$source = {}) {
        if (!("connection_id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["connection_id"] = "";
        }
        if (!("databases" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["databases"] = [];
        }
        if (!("database" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["database"] = "";
        }
        if (!("tables" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["tables"] = [];
        }
        if (!("output_dir" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["output_dir"] = "";
        }
        if (!("threads" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["threads"] = 0;
        }
        if (!("compression" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["compression"] = "";
        }
        if (!("chunk_size" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["chunk_size"] = "";
        }
        if (!("skip_definer" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["skip_definer"] = false;
        }
        if (!("skip_binlog" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["skip_binlog"] = false;
        }
        if (!("include_schemas" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["include_schemas"] = [];
        }
        if (!("exclude_schemas" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["exclude_schemas"] = [];
        }
        if (!("include_tables" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["include_tables"] = [];
        }
        if (!("exclude_tables" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["exclude_tables"] = [];
        }
        if (!("overwrite" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["overwrite"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ExportRequest instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ExportRequest}
     */
    static createFrom($$source = {}) {
        const $$createField1_0 = $$createType2;
        const $$createField3_0 = $$createType2;
        const $$createField10_0 = $$createType2;
        const $$createField11_0 = $$createType2;
        const $$createField12_0 = $$createType2;
        const $$createField13_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("databases" in $$parsedSource) {
            $$parsedSource["databases"] = $$createField1_0($$parsedSource["databases"]);
        }
        if ("tables" in $$parsedSource) {
            $$parsedSource["tables"] = $$createField3_0($$parsedSource["tables"]);
        }
        if ("include_schemas" in $$parsedSource) {
            $$parsedSource["include_schemas"] = $$createField10_0($$parsedSource["include_schemas"]);
        }
        if ("exclude_schemas" in $$parsedSource) {
            $$parsedSource["exclude_schemas"] = $$createField11_0($$parsedSource["exclude_schemas"]);
        }
        if ("include_tables" in $$parsedSource) {
            $$parsedSource["include_tables"] = $$createField12_0($$parsedSource["include_tables"]);
        }
        if ("exclude_tables" in $$parsedSource) {
            $$parsedSource["exclude_tables"] = $$createField13_0($$parsedSource["exclude_tables"]);
        }
        return new ExportRequest(/** @type {Partial<ExportRequest>} */($$parsedSource));
    }
}

/**
 * ExportResponse 导出响应结构
 */
export class ExportResponse {
    /**
     * Creates a new ExportResponse instance.
     * @param {Partial<ExportResponse>} [$$source = {}] - The source object to create the ExportResponse.
     */
    constructor($$source = {}) {
        if (!("success" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["success"] = false;
        }
        if (!("message" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["message"] = "";
        }
        if (!("path" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["path"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ExportResponse instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ExportResponse}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ExportResponse(/** @type {Partial<ExportResponse>} */($$parsedSource));
    }
}

/**
 * ImportRequest 导入请求结构
 */
export class ImportRequest {
    /**
     * Creates a new ImportRequest instance.
     * @param {Partial<ImportRequest>} [$$source = {}] - The source object to create the ImportRequest.
     */
    constructor($$source = {}) {
        if (!("connection_id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["connection_id"] = "";
        }
        if (!("database" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["database"] = "";
        }
        if (!("input_dir" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["input_dir"] = "";
        }
        if (!("threads" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["threads"] = 0;
        }
        if (!("schema" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["schema"] = "";
        }
        if (!("include_schemas" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["include_schemas"] = [];
        }
        if (!("exclude_schemas" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["exclude_schemas"] = [];
        }
        if (!("include_tables" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["include_tables"] = [];
        }
        if (!("exclude_tables" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["exclude_tables"] = [];
        }
        if (!("reset_progress" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["reset_progress"] = false;
        }
        if (!("wait_timeout" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["wait_timeout"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ImportRequest instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ImportRequest}
     */
    static createFrom($$source = {}) {
        const $$createField5_0 = $$createType2;
        const $$createField6_0 = $$createType2;
        const $$createField7_0 = $$createType2;
        const $$createField8_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("include_schemas" in $$parsedSource) {
            $$parsedSource["include_schemas"] = $$createField5_0($$parsedSource["include_schemas"]);
        }
        if ("exclude_schemas" in $$parsedSource) {
            $$parsedSource["exclude_schemas"] = $$createField6_0($$parsedSource["exclude_schemas"]);
        }
        if ("include_tables" in $$parsedSource) {
            $$parsedSource["include_tables"] = $$createField7_0($$parsedSource["include_tables"]);
        }
        if ("exclude_tables" in $$parsedSource) {
            $$parsedSource["exclude_tables"] = $$createField8_0($$parsedSource["exclude_tables"]);
        }
        return new ImportRequest(/** @type {Partial<ImportRequest>} */($$parsedSource));
    }
}

/**
 * ImportResponse 导入响应结构
 */
export class ImportResponse {
    /**
     * Creates a new ImportResponse instance.
     * @param {Partial<ImportResponse>} [$$source = {}] - The source object to create the ImportResponse.
     */
    constructor($$source = {}) {
        if (!("success" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["success"] = false;
        }
        if (!("message" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["message"] = "";
        }
        if (!("path" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["path"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ImportResponse instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ImportResponse}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ImportResponse(/** @type {Partial<ImportResponse>} */($$parsedSource));
    }
}

/**
 * MySQLDumpExportRequest mysqldump导出请求结构
 */
export class MySQLDumpExportRequest {
    /**
     * Creates a new MySQLDumpExportRequest instance.
     * @param {Partial<MySQLDumpExportRequest>} [$$source = {}] - The source object to create the MySQLDumpExportRequest.
     */
    constructor($$source = {}) {
        if (!("connection_id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["connection_id"] = "";
        }
        if (!("databases" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["databases"] = [];
        }
        if (!("database" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["database"] = "";
        }
        if (!("tables" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["tables"] = [];
        }
        if (!("output_dir" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["output_dir"] = "";
        }
        if (!("compression" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["compression"] = "";
        }
        if (!("single_transaction" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["single_transaction"] = false;
        }
        if (!("routines" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["routines"] = false;
        }
        if (!("events" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["events"] = false;
        }
        if (!("overwrite" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["overwrite"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MySQLDumpExportRequest instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {MySQLDumpExportRequest}
     */
    static createFrom($$source = {}) {
        const $$createField1_0 = $$createType2;
        const $$createField3_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("databases" in $$parsedSource) {
            $$parsedSource["databases"] = $$createField1_0($$parsedSource["databases"]);
        }
        if ("tables" in $$parsedSource) {
            $$parsedSource["tables"] = $$createField3_0($$parsedSource["tables"]);
        }
        return new MySQLDumpExportRequest(/** @type {Partial<MySQLDumpExportRequest>} */($$parsedSource));
    }
}

/**
 * MySQLDumpImportRequest mysqldump导入请求结构
 */
export class MySQLDumpImportRequest {
    /**
     * Creates a new MySQLDumpImportRequest instance.
     * @param {Partial<MySQLDumpImportRequest>} [$$source = {}] - The source object to create the MySQLDumpImportRequest.
     */
    constructor($$source = {}) {
        if (!("connection_id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["connection_id"] = "";
        }
        if (!("input_file" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["input_file"] = "";
        }
        if (!("database" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["database"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MySQLDumpImportRequest instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {MySQLDumpImportRequest}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new MySQLDumpImportRequest(/** @type {Partial<MySQLDumpImportRequest>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = tools$0.ImportConflict.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = $Create.Array($Create.Any);
