// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ProcessService 进程管理 Wails 服务
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as tools$0 from "./internal/tools/models.js";

/**
 * GetSystemProcessInfos 获取系统进程信息列表
 * @returns {$CancellablePromise<tools$0.ProcessInfo[]>}
 */
export function GetSystemProcessInfos() {
    return $Call.ByID(425970279).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * Greet 问候用户（示例方法，保留兼容性）
 * @param {string} name
 * @returns {$CancellablePromise<string>}
 */
export function Greet(name) {
    return $Call.ByID(3458078461, name);
}

/**
 * KillProcessByPID 终止进程
 * @param {number} pid
 * @returns {$CancellablePromise<void>}
 */
export function KillProcessByPID(pid) {
    return $Call.ByID(773437893, pid);
}

/**
 * SearchPidByKeyWord 搜索进程
 * @param {string} keyword
 * @returns {$CancellablePromise<tools$0.ProcessInfo>}
 */
export function SearchPidByKeyWord(keyword) {
    return $Call.ByID(864573935, keyword).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * Startup 应用启动时由 Wails 调用
 * @returns {$CancellablePromise<void>}
 */
export function Startup() {
    return $Call.ByID(1801796309);
}

// Private type creation functions
const $$createType0 = tools$0.ProcessInfo.createFrom;
const $$createType1 = $Create.Array($$createType0);
