// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * DatabaseConnection 数据库连接配置
 */
export class DatabaseConnection {
    /**
     * Creates a new DatabaseConnection instance.
     * @param {Partial<DatabaseConnection>} [$$source = {}] - The source object to create the DatabaseConnection.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("host" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["host"] = "";
        }
        if (!("port" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["port"] = 0;
        }
        if (!("user" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["user"] = "";
        }
        if (!("password" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["password"] = "";
        }
        if (!("database" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["database"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DatabaseConnection instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {DatabaseConnection}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DatabaseConnection(/** @type {Partial<DatabaseConnection>} */($$parsedSource));
    }
}

/**
 * ExportSettings 导出设置
 */
export class ExportSettings {
    /**
     * Creates a new ExportSettings instance.
     * @param {Partial<ExportSettings>} [$$source = {}] - The source object to create the ExportSettings.
     */
    constructor($$source = {}) {
        if (!("export_tool" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["export_tool"] = "";
        }
        if (!("export_path" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["export_path"] = "";
        }
        if (!("last_connection_id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["last_connection_id"] = "";
        }
        if (!("last_databases" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["last_databases"] = [];
        }
        if (!("last_database" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["last_database"] = "";
        }
        if (!("last_tables" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["last_tables"] = [];
        }
        if (!("mysql_shell" in $$source)) {
            /**
             * @member
             * @type {MySQLShellConfig}
             */
            this["mysql_shell"] = (new MySQLShellConfig());
        }
        if (!("mysql_dump" in $$source)) {
            /**
             * @member
             * @type {MySQLDumpConfig}
             */
            this["mysql_dump"] = (new MySQLDumpConfig());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ExportSettings instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ExportSettings}
     */
    static createFrom($$source = {}) {
        const $$createField3_0 = $$createType0;
        const $$createField5_0 = $$createType0;
        const $$createField6_0 = $$createType1;
        const $$createField7_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("last_databases" in $$parsedSource) {
            $$parsedSource["last_databases"] = $$createField3_0($$parsedSource["last_databases"]);
        }
        if ("last_tables" in $$parsedSource) {
            $$parsedSource["last_tables"] = $$createField5_0($$parsedSource["last_tables"]);
        }
        if ("mysql_shell" in $$parsedSource) {
            $$parsedSource["mysql_shell"] = $$createField6_0($$parsedSource["mysql_shell"]);
        }
        if ("mysql_dump" in $$parsedSource) {
            $$parsedSource["mysql_dump"] = $$createField7_0($$parsedSource["mysql_dump"]);
        }
        return new ExportSettings(/** @type {Partial<ExportSettings>} */($$parsedSource));
    }
}

/**
 * MySQLDumpConfig mysqldump 导出配置
 */
export class MySQLDumpConfig {
    /**
     * Creates a new MySQLDumpConfig instance.
     * @param {Partial<MySQLDumpConfig>} [$$source = {}] - The source object to create the MySQLDumpConfig.
     */
    constructor($$source = {}) {
        if (!("compression" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["compression"] = "";
        }
        if (!("single_transaction" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["single_transaction"] = false;
        }
        if (!("routines" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["routines"] = false;
        }
        if (!("events" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["events"] = false;
        }
        if (!("overwrite" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["overwrite"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MySQLDumpConfig instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {MySQLDumpConfig}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new MySQLDumpConfig(/** @type {Partial<MySQLDumpConfig>} */($$parsedSource));
    }
}

/**
 * MySQLShellConfig MySQL Shell 导出配置
 */
export class MySQLShellConfig {
    /**
     * Creates a new MySQLShellConfig instance.
     * @param {Partial<MySQLShellConfig>} [$$source = {}] - The source object to create the MySQLShellConfig.
     */
    constructor($$source = {}) {
        if (!("threads" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["threads"] = 0;
        }
        if (!("compression" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["compression"] = "";
        }
        if (!("chunk_size" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["chunk_size"] = "";
        }
        if (!("skip_definer" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["skip_definer"] = false;
        }
        if (!("skip_binlog" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["skip_binlog"] = false;
        }
        if (!("overwrite" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["overwrite"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MySQLShellConfig instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {MySQLShellConfig}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new MySQLShellConfig(/** @type {Partial<MySQLShellConfig>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = MySQLShellConfig.createFrom;
const $$createType2 = MySQLDumpConfig.createFrom;
