// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetSystemProcessInfos() {
  return window['go']['main']['App']['GetSystemProcessInfos']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function KillProcessByPID(arg1) {
  return window['go']['main']['App']['KillProcessByPID'](arg1);
}

export function SearchPidByKeyWord(arg1) {
  return window['go']['main']['App']['SearchPidByKeyWord'](arg1);
}
