// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddDatabaseConnection(arg1) {
  return window['go']['main']['App']['AddDatabaseConnection'](arg1);
}

export function ConnectDatabase(arg1) {
  return window['go']['main']['App']['ConnectDatabase'](arg1);
}

export function DeleteDatabaseConnection(arg1) {
  return window['go']['main']['App']['DeleteDatabaseConnection'](arg1);
}

export function ExportDatabases(arg1) {
  return window['go']['main']['App']['ExportDatabases'](arg1);
}

export function ExportTables(arg1) {
  return window['go']['main']['App']['ExportTables'](arg1);
}

export function GetDatabaseConnection(arg1) {
  return window['go']['main']['App']['GetDatabaseConnection'](arg1);
}

export function GetDatabaseConnections() {
  return window['go']['main']['App']['GetDatabaseConnections']();
}

export function GetExportSettings() {
  return window['go']['main']['App']['GetExportSettings']();
}

export function GetSystemProcessInfos() {
  return window['go']['main']['App']['GetSystemProcessInfos']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function KillProcessByPID(arg1) {
  return window['go']['main']['App']['KillProcessByPID'](arg1);
}

export function ListDatabases(arg1) {
  return window['go']['main']['App']['ListDatabases'](arg1);
}

export function ListTables(arg1) {
  return window['go']['main']['App']['ListTables'](arg1);
}

export function SaveExportSettings(arg1) {
  return window['go']['main']['App']['SaveExportSettings'](arg1);
}

export function SearchPidByKeyWord(arg1) {
  return window['go']['main']['App']['SearchPidByKeyWord'](arg1);
}

export function SelectFolder() {
  return window['go']['main']['App']['SelectFolder']();
}

export function UpdateDatabaseConnection(arg1) {
  return window['go']['main']['App']['UpdateDatabaseConnection'](arg1);
}
