// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddDatabaseConnection(arg1) {
  return window['go']['main']['App']['AddDatabaseConnection'](arg1);
}

export function CheckImportConflicts(arg1) {
  return window['go']['main']['App']['CheckImportConflicts'](arg1);
}

export function ConnectDatabase(arg1) {
  return window['go']['main']['App']['ConnectDatabase'](arg1);
}

export function DeleteDatabaseConnection(arg1) {
  return window['go']['main']['App']['DeleteDatabaseConnection'](arg1);
}

export function DropConflictingTables(arg1) {
  return window['go']['main']['App']['DropConflictingTables'](arg1);
}

export function ExportDatabases(arg1) {
  return window['go']['main']['App']['ExportDatabases'](arg1);
}

export function ExportDatabasesMySQLDump(arg1) {
  return window['go']['main']['App']['ExportDatabasesMySQLDump'](arg1);
}

export function ExportTables(arg1) {
  return window['go']['main']['App']['ExportTables'](arg1);
}

export function ExportTablesMySQLDump(arg1) {
  return window['go']['main']['App']['ExportTablesMySQLDump'](arg1);
}

export function GetDatabaseConnection(arg1) {
  return window['go']['main']['App']['GetDatabaseConnection'](arg1);
}

export function GetDatabaseConnections() {
  return window['go']['main']['App']['GetDatabaseConnections']();
}

export function GetExportSettings() {
  return window['go']['main']['App']['GetExportSettings']();
}

export function GetSystemProcessInfos() {
  return window['go']['main']['App']['GetSystemProcessInfos']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function ImportDatabases(arg1) {
  return window['go']['main']['App']['ImportDatabases'](arg1);
}

export function ImportDumpMySQLDump(arg1) {
  return window['go']['main']['App']['ImportDumpMySQLDump'](arg1);
}

export function ImportTables(arg1) {
  return window['go']['main']['App']['ImportTables'](arg1);
}

export function KillProcessByPID(arg1) {
  return window['go']['main']['App']['KillProcessByPID'](arg1);
}

export function ListDatabases(arg1) {
  return window['go']['main']['App']['ListDatabases'](arg1);
}

export function ListDatabasesMySQLDump(arg1) {
  return window['go']['main']['App']['ListDatabasesMySQLDump'](arg1);
}

export function ListTables(arg1) {
  return window['go']['main']['App']['ListTables'](arg1);
}

export function ListTablesMySQLDump(arg1) {
  return window['go']['main']['App']['ListTablesMySQLDump'](arg1);
}

export function SaveExportSettings(arg1) {
  return window['go']['main']['App']['SaveExportSettings'](arg1);
}

export function SearchPidByKeyWord(arg1) {
  return window['go']['main']['App']['SearchPidByKeyWord'](arg1);
}

export function SelectFile() {
  return window['go']['main']['App']['SelectFile']();
}

export function SelectFolder() {
  return window['go']['main']['App']['SelectFolder']();
}

export function SelectSaveFile(arg1) {
  return window['go']['main']['App']['SelectSaveFile'](arg1);
}

export function UpdateDatabaseConnection(arg1) {
  return window['go']['main']['App']['UpdateDatabaseConnection'](arg1);
}
