// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {tools} from '../models';

export function GetSystemProcessInfos():Promise<Array<tools.ProcessInfo>>;

export function Greet(arg1:string):Promise<string>;

export function KillProcessByPID(arg1:number):Promise<void>;

export function SearchPidByKeyWord(arg1:string):Promise<tools.ProcessInfo>;
