// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {config} from '../models';
import {main} from '../models';
import {tools} from '../models';

export function AddDatabaseConnection(arg1:config.DatabaseConnection):Promise<void>;

export function ConnectDatabase(arg1:config.DatabaseConnection):Promise<void>;

export function DeleteDatabaseConnection(arg1:string):Promise<void>;

export function ExportDatabases(arg1:main.ExportRequest):Promise<main.ExportResponse>;

export function ExportTables(arg1:main.ExportRequest):Promise<main.ExportResponse>;

export function GetDatabaseConnection(arg1:string):Promise<config.DatabaseConnection>;

export function GetDatabaseConnections():Promise<Array<config.DatabaseConnection>>;

export function GetExportSettings():Promise<config.ExportSettings>;

export function GetSystemProcessInfos():Promise<Array<tools.ProcessInfo>>;

export function Greet(arg1:string):Promise<string>;

export function KillProcessByPID(arg1:number):Promise<void>;

export function ListDatabases(arg1:config.DatabaseConnection):Promise<Array<string>>;

export function ListTables(arg1:config.DatabaseConnection):Promise<Array<string>>;

export function SaveExportSettings(arg1:config.ExportSettings):Promise<void>;

export function SearchPidByKeyWord(arg1:string):Promise<tools.ProcessInfo>;

export function SelectFolder():Promise<string>;

export function UpdateDatabaseConnection(arg1:config.DatabaseConnection):Promise<void>;
